openapi: "3.0.0"
info:
  version: 1.0.0
  title: Upload & Download examples
x-package-name: com.github.slamdev.openapispringgenerator.showcase.server.api
x-api-name-prefix: UploadDownload
x-path-variable-name: server.url
#x-security-role: ROLE_USER
servers:
  - url: /api/files
paths:
  /:
    get:
      operationId: downloadOne
      responses:
        '200':
          description: OK
          content:
            image/png:
              schema:
                type: string
                format: binary
    post:
      operationId: uploadOne
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK
  /multipart:
    post:
      operationId: uploadMultipart
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UploadMultipart'
            encoding:
              fileName:
                contentType: image/png, image/jpeg
      responses:
        '200':
          description: OK
  /multiple:
    get:
      operationId: downloadMultiple
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DownloadMulti'
    post:
      operationId: uploadMultiple
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                filenames:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        '200':
          description: OK
components:
  schemas:
    UploadMultipart:
      type: object
      properties:
        orderId:
          type: integer
        userId:
          type: integer
        fileName:
          type: string
          format: binary
    DownloadMulti:
      type: object
      properties:
        username:
          type: string
        avatar:
          type: string
          format: byte
          description: Base64-encoded contents of the avatar image
        created:
          type: string
          format: date-time
    UploadMulti:
      type: object
      properties:
        filenames:
          type: array
          items:
            type: string
            format: binary
