name: build
on:
  push:
    branches:
      - main
    tags:
      - '!*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew :plugin:build
      - run: ./gradlew build -x :plugin:build
