name: release
on:
  push:
    branches:
      - '!*'
    tags:
      - '*.*.*'
jobs:
  plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - run: |
          echo "version=${GITHUB_REF##*/}" >> gradle.properties
          echo "gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}" >> gradle.properties
          echo "gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}" >> gradle.properties
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew :plugin:publishPlugins
  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - run: |
          echo "version=${GITHUB_REF##*/}" >> gradle.properties
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew :cli:publish
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: mv cli/build/libs/cli-*.jar cli/build/libs/cli.jar
      - uses: softprops/action-gh-release@v2
        with:
          files: cli/build/libs/cli.jar
          fail_on_unmatched_files: true
