name: release
on:
  push:
    branches:
      - '!*'
    tags:
      - '*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    name: release
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: |
          echo "version=${GITHUB_REF##*/}" > gradle.properties
          echo "gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}" > gradle.properties
          echo "gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}" > gradle.properties
      - uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: :plugin:publishPlugins
