name: release
on:
  push:
    branches:
      - '!*'
    tags:
      - '*.*.*'
jobs:
  plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: |
          echo "version=${GITHUB_REF##*/}" >> gradle.properties
          echo "gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}" >> gradle.properties
          echo "gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}" >> gradle.properties
      - uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: :plugin:publishPlugins
  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: |
          echo "version=${GITHUB_REF##*/}" >> gradle.properties
      - uses: eskatos/gradle-command-action@v1
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dependencies-cache-enabled: true
          arguments: :cli:publish
